name: Create Markdown Resume

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Convert Resume
      - uses: docker://pandoc/latex:2.9
        with:
          args: >-  # args on next lines
            --standalone
            resume.tex
            --output=README.md